let stores = [
  // {
  //   paging: { total: 100, offset: 0, limit: 50, returned: 50 },
  //   stores: [
  {
    recommendation: {},
    storeNumber: "57499-291591",
    id: "1024748",
    name: "Emio Nerima",
    phoneNumber: null,
    coordinates: { latitude: 35.737833, longitude: 139.653394 },
    regulations: [],
    address: {
      streetAddressLine1: "1-3-5 Nerima",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Nerima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "176-0001",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-3-5 Nerima", "Nerima-ku, 13 176-0001"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "emio-nerima-1-3-5-nerima-nerima-ku-13-176-0001-jp",
  },
  {
    recommendation: {},
    storeNumber: "30553-95663",
    id: "3537",
    name: "Toshimaen Eki-mae",
    phoneNumber: null,
    coordinates: { latitude: 35.743123, longitude: 139.647914 },
    regulations: [],
    address: {
      streetAddressLine1: "4-18-8 Nerima",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Nerima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "176-0001",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["4-18-8 Nerima", "Nerima-ku, 13 176-0001"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "toshimaen-eki-mae-4-18-8-nerima-nerima-ku-13-176-0001-jp",
  },
  {
    recommendation: {},
    storeNumber: "30821-102810",
    id: "4299",
    name: "Nihon University Itabashi Hospital",
    phoneNumber: null,
    coordinates: { latitude: 35.749459, longitude: 139.691765 },
    regulations: [],
    address: {
      streetAddressLine1: "30-1 Oyaguchikamicho",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Itabashi-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "173-0032",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["30-1 Oyaguchikamicho", "Itabashi-ku, 13 173-0032"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "nihon-university-itabashi-hospital-30-1-oyaguchikamicho-itabashi-ku-13-173-0032-jp",
  },
  {
    recommendation: {},
    storeNumber: "30215-45359",
    id: "3975",
    name: "Nakano-dori",
    phoneNumber: null,
    coordinates: { latitude: 35.706849, longitude: 139.665419 },
    regulations: [],
    address: {
      streetAddressLine1: "5-64-5 Nakano",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Nakano-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "164-0001",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["5-64-5 Nakano", "Nakano-ku, 13 164-0001"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "nakano-dori-5-64-5-nakano-nakano-ku-13-164-0001-jp",
  },
  {
    recommendation: {},
    storeNumber: "30126-13534",
    id: "3906",
    name: "AEON Itabashi",
    phoneNumber: "81-3-3933-1067",
    coordinates: { latitude: 35.769618, longitude: 139.66109 },
    regulations: [],
    address: {
      streetAddressLine1: "2-6-1 Tokumaru",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Itabashi-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "175-0083",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["2-6-1 Tokumaru", "Itabashi-ku, 13 175-0083"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "aeon-itabashi-2-6-1-tokumaru-itabashi-ku-13-175-0083-jp",
  },
  {
    recommendation: {},
    storeNumber: "23617-231665",
    id: "1011159",
    name: "Echika Ikebukuro",
    phoneNumber: null,
    coordinates: { latitude: 35.731318, longitude: 139.707626 },
    regulations: [],
    address: {
      streetAddressLine1: "3-28-14 Nishiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-0021",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-28-14 Nishiikebukuro", "Toshima-ku, 13 171-0021"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "echika-ikebukuro-3-28-14-nishiikebukuro-toshima-ku-13-171-0021-jp",
  },
  {
    recommendation: {},
    storeNumber: "30355-73981",
    id: "3737",
    name: "Ikebukuro nishiguchi",
    phoneNumber: null,
    coordinates: { latitude: 35.731049, longitude: 139.70876 },
    regulations: [],
    address: {
      streetAddressLine1: "1-17-10 Nishiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-0021",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-17-10 Nishiikebukuro", "Toshima-ku, 13 171-0021"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "ikebukuro-nishiguchi-1-17-10-nishiikebukuro-toshima-ku-13-171-0021-jp",
  },
  {
    recommendation: {},
    storeNumber: "58402-292582",
    id: "1024965",
    name: "LUMINE Ikebukuro 9F",
    phoneNumber: null,
    coordinates: { latitude: 35.728867, longitude: 139.709291 },
    regulations: [],
    address: {
      streetAddressLine1: "1-11-1 Nishiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-0021",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-11-1 Nishiikebukuro", "Toshima-ku, 13 171-0021"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "lumine-ikebukuro-9-f-1-11-1-nishiikebukuro-toshima-ku-13-171-0021-jp",
  },
  {
    recommendation: {},
    storeNumber: "16082-167324",
    id: "66443",
    name: "LUMINE Ikebukuro",
    phoneNumber: null,
    coordinates: { latitude: 35.729275, longitude: 139.709718 },
    regulations: [],
    address: {
      streetAddressLine1: "1-11-1 Nishiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-0021",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-11-1 Nishiikebukuro", "Toshima-ku, 13 171-0021"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "lumine-ikebukuro-1-11-1-nishiikebukuro-toshima-ku-13-171-0021-jp",
  },
  {
    recommendation: {},
    storeNumber: "17073-172466",
    id: "91089",
    name: "Tobu Ikebukuro",
    phoneNumber: null,
    coordinates: { latitude: 35.730136, longitude: 139.710286 },
    regulations: [],
    address: {
      streetAddressLine1: "1-1-25 Nishiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-8512",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-1-25 Nishiikebukuro", "Toshima-ku, 13 171-8512"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "tobu-ikebukuro-1-1-25-nishiikebukuro-toshima-ku-13-171-8512-jp",
  },
  {
    recommendation: {},
    storeNumber: "56812-290791",
    id: "1023434",
    name: "JR Ikebukuro Eki Nishiguchi",
    phoneNumber: null,
    coordinates: { latitude: 35.73034, longitude: 139.710564 },
    regulations: [],
    address: {
      streetAddressLine1: "1-1-25 Nishiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-0021",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["1-1-25 Nishiikebukuro", "Toshima-ku, 13 171-0021"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "jr-ikebukuro-eki-nishiguchi-1-1-25-nishiikebukuro-toshima-ku-13-171-0021-jp",
  },
  {
    recommendation: {},
    storeNumber: "30068-12752",
    id: "3730",
    name: "Ikebukuro Meiji-dori",
    phoneNumber: "81-3-3590-0065",
    coordinates: { latitude: 35.727822, longitude: 139.711786 },
    regulations: [],
    address: {
      streetAddressLine1: "1-18-17 Minamiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-18-17 Minamiikebukuro", "Toshima-ku, 13 171-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "ikebukuro-meiji-dori-1-18-17-minamiikebukuro-toshima-ku-13-171-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "30572-97742",
    id: "3494",
    name: "Ikebukuro Shopping Park",
    phoneNumber: null,
    coordinates: { latitude: 35.730135, longitude: 139.712685 },
    regulations: [],
    address: {
      streetAddressLine1: "1-29-1 Minamiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-29-1 Minamiikebukuro", "Toshima-ku, 13 171-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "ikebukuro-shopping-park-1-29-1-minamiikebukuro-toshima-ku-13-171-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "30163-29056",
    id: "3950",
    name: "Minamiikebukuro",
    phoneNumber: "03-5391-0089",
    coordinates: { latitude: 35.727057, longitude: 139.712371 },
    regulations: [],
    address: {
      streetAddressLine1: "2-16-4 Minamiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["2-16-4 Minamiikebukuro", "Toshima-ku, 13 171-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "minamiikebukuro-2-16-4-minamiikebukuro-toshima-ku-13-171-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "30054-11658",
    id: "3998",
    name: "Seibu Takadanobaba Eki",
    phoneNumber: "81-3-5291-2931",
    coordinates: { latitude: 35.712991, longitude: 139.704112 },
    regulations: [],
    address: {
      streetAddressLine1: "1-35-2 Takadanobaba",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "169-0075",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-35-2 Takadanobaba", "Shinjuku-ku, 13 169-0075"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "seibu-takadanobaba-eki-1-35-2-takadanobaba-shinjuku-ku-13-169-0075-jp",
  },
  {
    recommendation: {},
    storeNumber: "31989-126367",
    id: "4327",
    name: "Ikebukuro Sunshine-dori",
    phoneNumber: null,
    coordinates: { latitude: 35.730817, longitude: 139.715441 },
    regulations: [],
    address: {
      streetAddressLine1: "1-20-5 Higashiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "170-0013",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-20-5 Higashiikebukuro", "Toshima-ku, 13 170-0013"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "ikebukuro-sunshine-dori-1-20-5-higashiikebukuro-toshima-ku-13-170-0013-jp",
  },
  {
    recommendation: {},
    storeNumber: "30428-79240",
    id: "4100",
    name: "Asagaya Eki-mae",
    phoneNumber: null,
    coordinates: { latitude: 35.704819, longitude: 139.635647 },
    regulations: [],
    address: {
      streetAddressLine1: "3-58-1 Asagayaminami",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Suginami-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "166-0004",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-58-1 Asagayaminami", "Suginami-ku, 13 166-0004"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "asagaya-eki-mae-3-58-1-asagayaminami-suginami-ku-13-166-0004-jp",
  },
  {
    recommendation: {},
    storeNumber: "30171-31120",
    id: "3952",
    name: "Takadanobaba Waseda-dori",
    phoneNumber: "03-3207-5800",
    coordinates: { latitude: 35.712252, longitude: 139.706623 },
    regulations: [],
    address: {
      streetAddressLine1: "1-25-32 Takadanobaba",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "169-0075",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-25-32 Takadanobaba", "Shinjuku-ku, 13 169-0075"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "takadanobaba-waseda-dori-1-25-32-takadanobaba-shinjuku-ku-13-169-0075-jp",
  },
  {
    recommendation: {},
    storeNumber: "51368-278230",
    id: "1018563",
    name: "Beans Asagaya Tekute",
    phoneNumber: null,
    coordinates: { latitude: 35.704822, longitude: 139.63401 },
    regulations: [],
    address: {
      streetAddressLine1: "Beans Asagaya Tekute 2-42 Asagayaminami",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Suginami-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "166-0004",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: [
      "Beans Asagaya Tekute 2-42 Asagayaminami",
      "Suginami-ku, 13 166-0004",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "beans-asagaya-tekute-beans-asagaya-tekute-2-42-asagayaminami-suginami-k",
  },
  {
    recommendation: {},
    storeNumber: "49473-256635",
    id: "1017963",
    name: "Nakanosakaue METROPIA",
    phoneNumber: null,
    coordinates: { latitude: 35.696695, longitude: 139.680854 },
    regulations: [],
    address: {
      streetAddressLine1: "2-48-2 Honcho Nakano-ku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Tokyo",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "164-0012",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["2-48-2 Honcho Nakano-ku", "Tokyo, 13 164-0012"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "nakanosakaue-metropia-2-48-2-honcho-nakano-ku-tokyo-13-164-0012-jp",
  },
  {
    recommendation: {},
    storeNumber: "51687-279064",
    id: "1018988",
    name: "Ikebukuro Shopping Park Kitakan",
    phoneNumber: null,
    coordinates: { latitude: 35.724814, longitude: 139.715866 },
    regulations: [],
    address: {
      streetAddressLine1: "Ikebukuro Shopping Park",
      streetAddressLine2: "1-29-1 Minamiikebukuro",
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "171-8532",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: [
      "Ikebukuro Shopping Park",
      "1-29-1 Minamiikebukuro",
      "Toshima-ku, 13 171-8532",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "ikebukuro-shopping-park-kitakan-ikebukuro-shopping-park-toshima-ku-13-171-8532-jp",
  },
  {
    recommendation: {},
    storeNumber: "30314-66741",
    id: "3958",
    name: "Ikebukuro Sunshine City alpa",
    phoneNumber: null,
    coordinates: { latitude: 35.729828, longitude: 139.718032 },
    regulations: [],
    address: {
      streetAddressLine1: "3-1-1 Higashiikebukuro",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "170-6090",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-1-1 Higashiikebukuro", "Toshima-ku, 13 170-6090"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "ikebukuro-sunshine-city-alpa-3-1-1-higashiikebukuro-toshima-ku-13-170-6090-jp",
  },
  {
    recommendation: {},
    storeNumber: "30055-11659",
    id: "3945",
    name: "Nishishinjuku Mitsui Bldg.",
    phoneNumber: "81-3-5323-5631",
    coordinates: { latitude: 35.6952, longitude: 139.689005 },
    regulations: [],
    address: {
      streetAddressLine1: "6-24-1 Nishishinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0023",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["6-24-1 Nishishinjuku", "Shinjuku-ku, 13 160-0023"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "nishishinjuku-mitsui-bldg-6-24-1-nishishinjuku-shinjuku-ku-13-160-0023-jp",
  },
  {
    recommendation: {},
    storeNumber: "30227-38799",
    id: "3986",
    name: "Shinjuku Green Tower Bldg.",
    phoneNumber: null,
    coordinates: { latitude: 35.692273, longitude: 139.689605 },
    regulations: [],
    address: {
      streetAddressLine1: "6-14-1 Nishishinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0023",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["6-14-1 Nishishinjuku", "Shinjuku-ku, 13 160-0023"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "shinjuku-green-tower-bldg-6-14-1-nishishinjuku-shinjuku-ku-13-160-0023-jp",
  },
  {
    recommendation: {},
    storeNumber: "28486-247907",
    id: "1014601",
    name: "Tobu Narimasu Eki",
    phoneNumber: null,
    coordinates: { latitude: 35.777581, longitude: 139.632947 },
    regulations: [],
    address: {
      streetAddressLine1: "2-13-1 Narimasu",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Itabashi-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "175-0094",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["2-13-1 Narimasu", "Itabashi-ku, 13 175-0094"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "tobu-narimasu-eki-2-13-1-narimasu-itabashi-ku-13-175-0094-jp",
  },
  {
    recommendation: {},
    storeNumber: "31833-123366",
    id: "4313",
    name: "LUMINE Ogikubo",
    phoneNumber: null,
    coordinates: { latitude: 35.704666, longitude: 139.620316 },
    regulations: [],
    address: {
      streetAddressLine1: "1-7-1 Kamiogi",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Suginami-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "167-0043",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-7-1 Kamiogi", "Suginami-ku, 13 167-0043"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "lumine-ogikubo-1-7-1-kamiogi-suginami-ku-13-167-0043-jp",
  },
  {
    recommendation: {},
    storeNumber: "59201-293435",
    id: "1025711",
    name: "Ogikubo TOWN SEVEN",
    phoneNumber: null,
    coordinates: { latitude: 35.705124, longitude: 139.619699 },
    regulations: [],
    address: {
      streetAddressLine1: "1-9-1 Kamiogi",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Suginami-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "167-0043",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-9-1 Kamiogi", "Suginami-ku, 13 167-0043"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "ogikubo-town-seven-1-9-1-kamiogi-suginami-ku-13-167-0043-jp",
  },
  {
    recommendation: {},
    storeNumber: "3683-143386",
    id: "3659",
    name: "Shinjuku Nomura Bldg.",
    phoneNumber: null,
    coordinates: { latitude: 35.692997, longitude: 139.695252 },
    regulations: [],
    address: {
      streetAddressLine1: "1-26-2 Nishishinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "163-0590",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-26-2 Nishishinjuku", "Shinjuku-ku, 13 163-0590"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "shinjuku-nomura-bldg-1-26-2-nishishinjuku-shinjuku-ku-13-163-0590-jp",
  },
  {
    recommendation: {},
    storeNumber: "30475-84912",
    id: "4133",
    name: "Seibu Shinjuku PePe",
    phoneNumber: null,
    coordinates: { latitude: 35.694491, longitude: 139.700191 },
    regulations: [],
    address: {
      streetAddressLine1: "1-30-1 Kabukicho",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0021",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-30-1 Kabukicho", "Shinjuku-ku, 13 160-0021"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "seibu-shinjuku-pe-pe-1-30-1-kabukicho-shinjuku-ku-13-160-0021-jp",
  },
  {
    recommendation: {},
    storeNumber: "32773-138809",
    id: "3626",
    name: "Shinjuku Mitsui Bldg.",
    phoneNumber: null,
    coordinates: { latitude: 35.691509, longitude: 139.693877 },
    regulations: [],
    address: {
      streetAddressLine1: "2-1-1 Nishishinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "163-0413",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["2-1-1 Nishishinjuku", "Shinjuku-ku, 13 163-0413"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-mitsui-bldg-2-1-1-nishishinjuku-shinjuku-ku-13-163-0413-jp",
  },
  {
    recommendation: {},
    storeNumber: "18616-191888",
    id: "1005813",
    name: "atre vie Otsuka",
    phoneNumber: null,
    coordinates: { latitude: 35.731247, longitude: 139.728932 },
    regulations: [],
    address: {
      streetAddressLine1: "3-33-1 Minamiotsuka",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Toshima-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "170-0005",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-33-1 Minamiotsuka", "Toshima-ku, 13 170-0005"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "atre-vie-otsuka-3-33-1-minamiotsuka-toshima-ku-13-170-0005-jp",
  },
  {
    recommendation: {},
    storeNumber: "30427-81175",
    id: "3864",
    name: "Shinjuku L Tower",
    phoneNumber: null,
    coordinates: { latitude: 35.692254, longitude: 139.697489 },
    regulations: [],
    address: {
      streetAddressLine1: "1-6-1 Nishishinnjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "163-1590",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-6-1 Nishishinnjuku", "Shinjuku-ku, 13 163-1590"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-l-tower-1-6-1-nishishinnjuku-shinjuku-ku-13-163-1590-jp",
  },
  {
    recommendation: {},
    storeNumber: "32015-126365",
    id: "4330",
    name: "Shinjuku Subnade",
    phoneNumber: null,
    coordinates: { latitude: 35.693902, longitude: 139.701111 },
    regulations: [],
    address: {
      streetAddressLine1: "Subnade 1 Kabukicho",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0021",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["Subnade 1 Kabukicho", "Shinjuku-ku, 13 160-0021"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-subnade-subnade-1-kabukicho-shinjuku-ku-13-160-0021-jp",
  },
  {
    recommendation: {},
    storeNumber: "57407-267935",
    id: "1024820",
    name: "Waseda University Toyama Campus",
    phoneNumber: null,
    coordinates: { latitude: 35.705387, longitude: 139.717425 },
    regulations: [],
    address: {
      streetAddressLine1: "1-24-1 Toyama",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "162-8644",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-24-1 Toyama", "Shinjuku-ku, 13 162-8644"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "waseda-university-toyama-campus-1-24-1-toyama-shinjuku-ku-13-162-8644-jp",
  },
  {
    recommendation: {},
    storeNumber: "19709-201524",
    id: "1005333",
    name: "Odakyu Shinjuku",
    phoneNumber: null,
    coordinates: { latitude: 35.691264, longitude: 139.699361 },
    regulations: [],
    address: {
      streetAddressLine1: "1-1-3 Nishishinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-8001",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-1-3 Nishishinjuku", "Shinjuku-ku, 13 160-8001"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "odakyu-shinjuku-1-1-3-nishishinjuku-shinjuku-ku-13-160-8001-jp",
  },
  {
    recommendation: {},
    storeNumber: "59635-293885",
    id: "1025927",
    name: "Shinjuku MYLORD 5F",
    phoneNumber: null,
    coordinates: { latitude: 35.691322, longitude: 139.6995 },
    regulations: [],
    address: {
      streetAddressLine1: "1-1-3 Nishi-shinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0023",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-1-3 Nishi-shinjuku", "Shinjuku-ku, 13 160-0023"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-mylord-5-f-1-1-3-nishi-shinjuku-shinjuku-ku-13-160-0023-jp",
  },
  {
    recommendation: {},
    storeNumber: "31947-240830",
    id: "1011577",
    name: "LUMINE Shinjuku EST",
    phoneNumber: null,
    coordinates: { latitude: 35.691736, longitude: 139.701118 },
    regulations: [],
    address: {
      streetAddressLine1: "3-38-1 Shinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-38-1 Shinjuku", "Shinjuku-ku, 13 160-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "lumine-shinjuku-est-3-38-1-shinjuku-shinjuku-ku-13-160-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "31152-106236",
    id: "4268",
    name: "Shinjuku Nishiguchi",
    phoneNumber: null,
    coordinates: { latitude: 35.689958, longitude: 139.697391 },
    regulations: [],
    address: {
      streetAddressLine1: "1-12-1 Nishishinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0023",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-12-1 Nishishinjuku", "Shinjuku-ku, 13 160-0023"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-nishiguchi-1-12-1-nishishinjuku-shinjuku-ku-13-160-0023-jp",
  },
  {
    recommendation: {},
    storeNumber: "24125-281734",
    id: "1020535",
    name: "TSUTAYA BOOK APARTMENT Shinjuku",
    phoneNumber: null,
    coordinates: { latitude: 35.691776, longitude: 139.702433 },
    regulations: [],
    address: {
      streetAddressLine1: "3-26-14 Shinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["3-26-14 Shinjuku", "Shinjuku-ku, 13 160-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "tsutaya-book-apartment-shinjuku-3-26-14-shinjuku-shinjuku-ku-13-160-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "30226-37139",
    id: "3734",
    name: "Shinjuku Daian Bldg.",
    phoneNumber: null,
    coordinates: { latitude: 35.690309, longitude: 139.701798 },
    regulations: [],
    address: {
      streetAddressLine1: "3-36-6 Shinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-36-6 Shinjuku", "Shinjuku-ku, 13 160-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-daian-bldg-3-36-6-shinjuku-shinjuku-ku-13-160-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "30360-76020",
    id: "3911",
    name: "LUMINE Shinjuku",
    phoneNumber: null,
    coordinates: { latitude: 35.68903, longitude: 139.699165 },
    regulations: [],
    address: {
      streetAddressLine1: "1-1-5 Nishishinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0023",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-1-5 Nishishinjuku", "Shinjuku-ku, 13 160-0023"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "lumine-shinjuku-1-1-5-nishishinjuku-shinjuku-ku-13-160-0023-jp",
  },
  {
    recommendation: {},
    storeNumber: "26973-246304",
    id: "1012600",
    name: "SHINJUKU  MYLORD",
    phoneNumber: null,
    coordinates: { latitude: 35.689285, longitude: 139.699824 },
    regulations: [],
    address: {
      streetAddressLine1: "1-1-3 Nishishinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0023",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["1-1-3 Nishishinjuku", "Shinjuku-ku, 13 160-0023"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-mylord-1-1-3-nishishinjuku-shinjuku-ku-13-160-0023-jp",
  },
  {
    recommendation: {},
    storeNumber: "3679-139189",
    id: "4213",
    name: "Shinjuku Marui Honkan 2F",
    phoneNumber: null,
    coordinates: { latitude: 35.691013, longitude: 139.704082 },
    regulations: [],
    address: {
      streetAddressLine1: "3-30-13 Shinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-30-13 Shinjuku", "Shinjuku-ku, 13 160-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "shinjuku-marui-honkan-2-f-3-30-13-shinjuku-shinjuku-ku-13-160-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "4036-145073",
    id: "4212",
    name: "Shinjuku Marui Honkan 8F",
    phoneNumber: null,
    coordinates: { latitude: 35.690952, longitude: 139.704011 },
    regulations: [],
    address: {
      streetAddressLine1: "3-30-13 Shinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-30-13 Shinjuku", "Shinjuku-ku, 13 160-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "shinjuku-marui-honkan-8-f-3-30-13-shinjuku-shinjuku-ku-13-160-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "30012-9918",
    id: "3976",
    name: "Shinjuku 3-chome",
    phoneNumber: "81-3-3226-9201",
    coordinates: { latitude: 35.692068, longitude: 139.70633 },
    regulations: [],
    address: {
      streetAddressLine1: "3-11-6 Shinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-11-6 Shinjuku", "Shinjuku-ku, 13 160-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-3-chome-3-11-6-shinjuku-shinjuku-ku-13-160-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "30197-33226",
    id: "3920",
    name: "Shinjuku Minamiguchi",
    phoneNumber: null,
    coordinates: { latitude: 35.686947, longitude: 139.69608 },
    regulations: [],
    address: {
      streetAddressLine1: "2-13-8 Yoyogi",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shibuya-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "151-0053",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["2-13-8 Yoyogi", "Shibuya-ku, 13 151-0053"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-minamiguchi-2-13-8-yoyogi-shibuya-ku-13-151-0053-jp",
  },
  {
    recommendation: {},
    storeNumber: "30016-9922",
    id: "3872",
    name: "Shinjuku Southern Terrace",
    phoneNumber: "81-3-3370-3255",
    coordinates: { latitude: 35.687914, longitude: 139.700257 },
    regulations: [],
    address: {
      streetAddressLine1: "2-2-1 Yoyogi",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shibuya-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "151-0053",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["2-2-1 Yoyogi", "Shibuya-ku, 13 151-0053"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-southern-terrace-2-2-1-yoyogi-shibuya-ku-13-151-0053-jp",
  },
  {
    recommendation: {},
    storeNumber: "30317-67440",
    id: "3866",
    name: "Shinjuku Shinminamiguchi",
    phoneNumber: null,
    coordinates: { latitude: 35.68887, longitude: 139.702459 },
    regulations: [],
    address: {
      streetAddressLine1: "4-1-9 Shinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["4-1-9 Shinjuku", "Shinjuku-ku, 13 160-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-shinminamiguchi-4-1-9-shinjuku-shinjuku-ku-13-160-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "60680-295076",
    id: "1027387",
    name: "Keio Shinjuku 3-chome Building",
    phoneNumber: null,
    coordinates: { latitude: 35.690239, longitude: 139.705414 },
    regulations: [],
    address: {
      streetAddressLine1: "3-1-24 Shinjuku",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shinjuku-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "160-0022",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["3-1-24 Shinjuku", "Shinjuku-ku, 13 160-0022"],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "keio-shinjuku-3-chome-building-3-1-24-shinjuku-shinjuku-ku-13-160-0022-jp",
  },
  {
    recommendation: {},
    storeNumber: "30124-15793",
    id: "3905",
    name: "Shinjuku MAYNDS Tower",
    phoneNumber: "81-3-3373-3370",
    coordinates: { latitude: 35.686589, longitude: 139.698823 },
    regulations: [],
    address: {
      streetAddressLine1: "2-1-1 Yoyogi",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Shibuya-ku",
      countrySubdivisionCode: "13",
      countryCode: "JP",
      postalCode: "151-0053",
    },
    timeZoneInfo: {
      currentTimeOffset: 540,
      windowsTimeZoneId: "Tokyo Standard Time",
      olsonTimeZoneId: "GMT+09:00 Asia/Tokyo",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "CO",
    open: null,
    openStatusText: "",
    addressLines: ["2-1-1 Yoyogi", "Shibuya-ku, 13 151-0053"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "shinjuku-maynds-tower-2-1-1-yoyogi-shibuya-ku-13-151-0053-jp",
  },
];
//     ,
//     coordinates: { lat: 35.73706170000001, lng: 139.6662552 },
//     includesRecommendedLocations: false,
//   },
// ];
